### ISSUE TITLE
Connection to camera lost after some time (v1.2.102 )

### ISSUE THREAD

**Issue by Gaweringo** [andycb/AdventurerClientJS#34]
I have noticed the change in the way the app connects to the camera of the printer as a result of #28. I had the same problem, that the link to the camera feed would never show up. I downloaded the updated version and it is working now, for a while.

After some time (30 to 60min in my few tests) the app loses the connection to the camera.
In the Resource Monitor, lots of connections start showing up.
![Resource Monitor many Conenctions](https://user-images.githubusercontent.com/40121865/105613048-4ead0d00-5dc0-11eb-869d-63dc20292a75.png)
After some time they disappear.
![Resource Monitor one Connection](https://user-images.githubusercontent.com/40121865/105613056-5a003880-5dc0-11eb-8fa9-0536e834aa76.png)

After this happens I can't reconnect to the camera, not through Adventurer Client nor through VLC or the Browser.
I  have to turn the printer off and back on to enable it again.

**Comment by andycb** [comment]
Hi,

The greyed-out connections in resource monitor are recently released connections that are showed for a short while but are not consuming resources so should be fine: https://social.technet.microsoft.com/Forums/windowsserver/en-US/eb6d5598-674a-40f6-a9eb-9f298886b9ce/resource-monitor-tcp-connections

I’ll have to try leaving it running to see if any I can reproduce an issue here - It might be a firmware issue with the printer receiving so many connect / disconnect cycles.

There was a known issue in build 1.2.102 where it would leak connections over time while navigating but that should have been fixed in 1.2.109: 
https://github.com/andycb/AdventurerClientJS/releases/tag/v1.2.109-bu

**Comment by Gaweringo** [comment]
Haven't used the Resource Monitor much, only because I had seen it in the other issue. Good to know that the gray ones are released ones.

I didn't see the 1.2.109 build and thought that 1.2.102 was the latest build.
I've been running the stream in v1.2.109 for a few hours and it's still going. Seems like this issue is fixed.

Sorry for bothering you.

And I might have a feature request if it's possible to add a scanning feature like in Flashprint, which finds the IP-Adress for you.
(Should I make a new Issue?)

**Comment by andycb** [comment]
Hm, I'm beginning to think there's a bug in the printer firmware that causes it to get slower over time - eventually it delays the loading of data and times out causing the video feed to show an error. I think my only option here is to just remove that check altogether.

Thank for taking the time to test this.

The auto IP scanning was mentioned in #32 too but if you could open an issue for it specifically, please, it wil let me track all of the people who should be credited :)

**Comment by andycb** [comment]
I've given this problem some thought and reworked the way the app holds the connection to the printer and determines if teh camera becomes unavailable.

I've changes it so the app no longer polls the camera to check for availability, but instead holds a single connection the whole time. In Activity monitor you should see just the one connection on port 8899 and the other on port 8080. Hopefully this should stop the app from overwhelming the printer during long prints.

![image](https://user-images.githubusercontent.com/4417762/106527826-cc1efe80-64df-11eb-9f30-265e3825e451.png)

I've made the build for this PR available here f you want to try it: https://github.com/andycb/AdventurerClientJS/releases/tag/v1.2.117-bu
